apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::671581034425:role/sandbox-sit20210524112009155100000007
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::671581034425:user/john
      username: john
      groups:
      - system:basic-user
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  resourceVersion: "37265"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 748bfaeb-8537-4742-bd0e-6bcf720e86c1
